version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    restart: always
    ports:
      - "8000:8000"
      - "8080:8080"
      - "50051:50051"
    volumes:
      - .:/app
    depends_on:
      - mysql
      - rabbitmq

  mysql:
    image: mysql:5.7
    container_name: mysql
    platform: linux/amd64
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orders
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - .docker/mysql:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest